=== foxycom/dbts/conf/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="https://uni-passau.de" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="config" type="uni:configType" xmlns:uni="https://uni-passau.de"/>
  <xs:complexType name="eraseType">
    <xs:simpleContent>
      <xs:extension base="xs:boolean">
        <xs:attribute type="xs:integer" name="wait"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="dbSwitch">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TimescaleDB_Wide"/>
      <xs:enumeration value="TimescaleDB_Narrow"/>
      <xs:enumeration value="InfluxDB"/>
      <xs:enumeration value="CrateDB"/>
      <xs:enumeration value="KairosDB"/>
      <xs:enumeration value="Citus"/>
      <xs:enumeration value="MemSQL"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="dbType">
    <xs:sequence>
      <xs:element type="uni:dbSwitch" name="type" xmlns:uni="https://uni-passau.de"/>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="host"/>
      <xs:element type="xs:integer" name="port"/>
      <xs:element type="uni:eraseType" name="erase" xmlns:uni="https://uni-passau.de"/>
      <xs:element type="xs:boolean" name="createSchema"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="mysqlLogType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:boolean" name="active"/>
        <xs:attribute type="xs:string" name="remark"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="clientsType">
    <xs:simpleContent>
      <xs:extension base="xs:byte">
        <xs:attribute type="xs:boolean" name="bindToDevices"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:simpleType name="sensorCategory">
    <xs:restriction base="xs:string">
      <xs:enumeration value="basic"/>
      <xs:enumeration value="gps"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="sensorType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:integer" name="frequency" use="required"/>
        <xs:attribute type="uni:sensorCategory" name="type" use="required" xmlns:uni="https://uni-passau.de"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="sensorGroupType">
    <xs:sequence>
      <xs:element type="uni:sensorType" name="sensor" maxOccurs="unbounded" minOccurs="1" xmlns:uni="https://uni-passau.de"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="required"/>
    <xs:attribute type="xs:string" name="fields" />
    <xs:attribute type="xs:string" name="dataType" use="required"/>
  </xs:complexType>
  <xs:complexType name="sensorGroupsType">
    <xs:sequence>
      <xs:element type="uni:sensorGroupType" name="sensorGroup" maxOccurs="unbounded" minOccurs="1" xmlns:uni="https://uni-passau.de"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="prefix" use="required"/>
  </xs:complexType>
  <xs:complexType name="batchType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:integer" name="size"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="serverMonitorType">
    <xs:sequence>
      <xs:element type="xs:string" name="drive"/>
      <xs:element type="xs:string" name="iface"/>
      <xs:element type="xs:integer" name="port"/>
    </xs:sequence>
    <xs:attribute type="xs:boolean" name="active" use="required"/>
  </xs:complexType>
  <xs:complexType name="overflowType">
    <xs:sequence>
      <xs:element type="xs:float" name="ratio"/>
      <xs:element type="xs:float" name="lamda"/>
      <xs:element type="xs:int" name="maxK"/>
    </xs:sequence>
    <xs:attribute type="xs:boolean" name="active"/>
  </xs:complexType>
  <xs:complexType name="timestampType">
    <xs:sequence>
      <xs:element type="xs:integer" name="startIndex"/>
      <xs:element type="xs:integer" name="seed"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="lineType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:double" name="ratio"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="sinType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:double" name="ratio"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="squareType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:double" name="ratio"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="devicesType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="prefix"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="randomType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:double" name="ratio"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="modeType">
    <xs:simpleContent>
      <xs:restriction base="xs:string">
        <xs:enumeration value="server_mode"/>
        <xs:enumeration value="test_with_default_path"/>
        <xs:enumeration value="query_test_with_default_path"/>
      </xs:restriction>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="constantType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:double" name="ratio"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="functionsType">
    <xs:sequence>
      <xs:element type="uni:lineType" name="line" xmlns:uni="https://uni-passau.de"/>
      <xs:element type="uni:sinType" name="sin" xmlns:uni="https://uni-passau.de"/>
      <xs:element type="uni:squareType" name="square" xmlns:uni="https://uni-passau.de"/>
      <xs:element type="uni:randomType" name="random" xmlns:uni="https://uni-passau.de"/>
      <xs:element type="uni:constantType" name="constant" xmlns:uni="https://uni-passau.de"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="queryType">
    <xs:sequence>
      <xs:element type="xs:string" name="type"/>
      <xs:element type="xs:integer" name="sensorNum"/>
      <xs:element type="xs:integer" name="deviceNum"/>
      <xs:element type="xs:integer" name="seed"/>
      <xs:element type="xs:integer" name="step"/>
      <xs:element type="xs:integer" name="radius"/>
      <xs:element type="xs:string" name="aggregateFunction"/>
      <xs:element type="xs:long" name="interval"/>
      <xs:element type="xs:double" name="lowerLimit"/>
      <xs:element type="xs:string" name="emptyPrecisePointQuery"/>
      <xs:element type="xs:integer" name="timeBucket"/>
      <xs:element type="xs:integer" name="limitClause"/>
      <xs:element type="xs:integer" name="limitN"/>
      <xs:element type="xs:integer" name="limitOffset"/>
      <xs:element type="xs:integer" name="sLimitN"/>
      <xs:element type="xs:integer" name="sLimitOffset"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="configType">
    <xs:sequence>
      <xs:element type="xs:string" name="version"/>
      <xs:element type="uni:dbType" name="db" xmlns:uni="https://uni-passau.de"/>
      <xs:element type="uni:modeType" name="mode" xmlns:uni="https://uni-passau.de"/>
      <xs:element type="uni:mysqlLogType" name="mysqlLog" xmlns:uni="https://uni-passau.de" minOccurs="0"/>
      <xs:element type="uni:clientsType" name="clients" xmlns:uni="https://uni-passau.de" minOccurs="0"/>
      <xs:element type="xs:integer" name="deviceGroups" minOccurs="0"/>
      <xs:element type="uni:devicesType" name="devices" xmlns:uni="https://uni-passau.de" minOccurs="0"/>
      <xs:element type="xs:string" name="operationsProportion" minOccurs="0"/>
      <xs:element type="uni:sensorGroupsType" name="sensorGroups" xmlns:uni="https://uni-passau.de" minOccurs="0" />
      <xs:element type="uni:batchType" name="batch" xmlns:uni="https://uni-passau.de" minOccurs="0"/>
      <xs:element type="xs:integer" name="loops" minOccurs="0"/>
      <xs:element type="xs:integer" name="pointStep" minOccurs="0"/>
      <xs:element type="xs:string" name="encoding" minOccurs="0"/>
      <xs:element type="uni:serverMonitorType" name="serverMonitor" xmlns:uni="https://uni-passau.de"/>
      <xs:element type="xs:boolean" name="mulDevBatch" minOccurs="0"/>
      <xs:element type="uni:overflowType" name="overflow" xmlns:uni="https://uni-passau.de" minOccurs="0"/>
      <xs:element type="uni:timestampType" name="timestamp" xmlns:uni="https://uni-passau.de" minOccurs="0"/>
      <xs:element type="uni:functionsType" name="functions" xmlns:uni="https://uni-passau.de" minOccurs="0"/>
      <xs:element type="uni:queryType" name="query" xmlns:uni="https://uni-passau.de" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== foxycom/dbts/conf/griddb.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<config xmlns="https://uni-passau.de"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://uni-passau.de  config.xsd">
    <version>0.4.0</version>
    <db>
        <type>GridDB</type>
        <name>test</name>
        <host>127.0.0.1</host>
        <port>8123</port>
        <erase wait="5000">false</erase>
        <createSchema>false</createSchema>
    </db>
    <mode>test_with_default_path</mode>
    <mysqlLog active="false" remark="INGEST">
        jdbc:mysql://127.0.0.1:3306/benchmark?user=root&amp;password=MyStrongPassword&amp;useUnicode=true&amp;characterEncoding=UTF8&amp;useSSL=false
    </mysqlLog>
    <clients bindToDevices="true">1</clients>
    <deviceGroups>3</deviceGroups>
    <devices prefix="d_">1</devices>

    <!-- INGEST::PRECISE::LAST_TIME_ACTIVE::HEATMAP::DISTANCE_DRIVEN::LAST_POSITIONS::IDENTIFY_TRIPS::BIKES_IN_LOC::GPS_PATH::DOWNSAMPLE::OFFLINE_BIKES -->
    <operationsProportion>0:1:0:0:0:0:0:0:0:0:0</operationsProportion>

    <sensorGroups prefix="s_">
        <sensorGroup name="accelerometer" dataType="Float64">
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
        </sensorGroup>
        <sensorGroup name="gyroscope" dataType="Float64">
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
        </sensorGroup>
        <sensorGroup name="magneticField" dataType="Float64">
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
        </sensorGroup>
        <sensorGroup name="incline" dataType="Float64">
            <sensor frequency="10" type="basic"/>
        </sensorGroup>
        <sensorGroup name="force" dataType="Float64">
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
        </sensorGroup>
        <sensorGroup name="gps" fields="longitude, latitude" dataType="Float64">
            <sensor frequency="1" type="gps"/>
        </sensorGroup>
        <sensorGroup name="rotaryEncoder" dataType="Float64">
            <sensor frequency="10" type="basic"/>
            <sensor frequency="10" type="basic"/>
            <sensor frequency="10" type="basic"/>
            <sensor frequency="10" type="basic"/>
        </sensorGroup>
        <sensorGroup name="current" dataType="Float64">
            <sensor frequency="10" type="basic"/>
        </sensorGroup>
        <sensorGroup name="temperature" dataType="Float64">
            <sensor frequency="1" type="basic"/>
            <sensor frequency="1" type="basic"/>
            <sensor frequency="1" type="basic"/>
        </sensorGroup>
        <sensorGroup name="distance" dataType="Float64">
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
        </sensorGroup>
        <sensorGroup name="oximeter" dataType="Float64">
            <sensor frequency="10" type="basic"/>
        </sensorGroup>
        <sensorGroup name="pulse" dataType="Float64">
            <sensor frequency="1" type="basic"/>
        </sensorGroup>
        <sensorGroup name="skinConductance" dataType="Float64">
            <sensor frequency="10" type="basic"/>
        </sensorGroup>
        <sensorGroup name="humidity" dataType="Float64">
            <sensor frequency="1" type="basic"/>
        </sensorGroup>
        <sensorGroup name="pressure" dataType="Float64">
            <sensor frequency="1" type="basic"/>
        </sensorGroup>
        <sensorGroup name="sound" dataType="Float64">
            <sensor frequency="50" type="basic"/>
        </sensorGroup>
        <sensorGroup name="light" dataType="Float64">
            <sensor frequency="1" type="basic"/>
        </sensorGroup>
        <sensorGroup name="particles" dataType="Float64">
            <sensor frequency="1" type="basic"/>
        </sensorGroup>
        <sensorGroup name="airQuality" dataType="Float64">
            <sensor frequency="1" type="basic"/>
            <sensor frequency="1" type="basic"/>
            <sensor frequency="1" type="basic"/>
            <sensor frequency="1" type="basic"/>
            <sensor frequency="1" type="basic"/>
        </sensorGroup>
        <sensorGroup name="emg" dataType="Float64">
            <sensor frequency="50" type="basic"/>
            <sensor frequency="50" type="basic"/>
        </sensorGroup>
    </sensorGroups>

    <batch size="10000"/>
    <loops>1</loops>
    <encoding>gorilla</encoding>

    <serverMonitor active="false">
        <drive>sdb</drive>
        <iface>enp0s25</iface>
        <port>56565</port>
    </serverMonitor>

    <mulDevBatch>false</mulDevBatch>
    <overflow active="false">
        <ratio>0.5</ratio>
        <lamda>2200.0</lamda>
        <maxK>170000</maxK>
    </overflow>

    <timestamp>
        <startIndex>20</startIndex>
        <seed>666</seed>
    </timestamp>

    <query>
        <type>7</type>
        <sensorNum>1</sensorNum>
        <deviceNum>1</deviceNum>
        <seed>151658</seed>
        <step>1000</step>
        <radius>500</radius>
        <aggregateFunction>avg</aggregateFunction>
        <interval>100000</interval>
        <lowerLimit>1000</lowerLimit>
        <emptyPrecisePointQuery>false</emptyPrecisePointQuery>
        <timeBucket>300000</timeBucket>
        <limitClause>0</limitClause>
        <limitN>5</limitN>
        <limitOffset>5</limitOffset>
        <sLimitN>5</sLimitN>
        <sLimitOffset>5</sLimitOffset>
    </query>

</config>
